"""What is worth writing a unit test for, decided without asking a model."""
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path

log = logging.getLogger("qa.spec")


TIER_ROUTE = 1
TIER_PURE_COMPONENT = 2
TIER_PURE_LIB = 3
TIER_INTERACTIVE = 4

MAX_PER_PHASE = 4


MAX_PER_PROJECT = 30


GENERATED = frozenset({
    "package.json", "next.config.mjs", "jsconfig.json", "tailwind.config.js",
    "postcss.config.js", "app/globals.css", "app/layout.jsx", "app/page.jsx",
    "lib/mongodb.js", "app/api/health/route.js", ".env.local", ".gitignore",
    "lib/auth.js", "lib/auth-client.js", "app/api/auth/[...all]/route.js",
    "AGENTS.md", "CLAUDE.md",
})


UNTESTABLE_LIB = frozenset({
    "lib/mongodb.js", "lib/auth.js", "lib/auth-client.js", "lib/seed.js",
})

ROUTE_RE = re.compile(r"^app/(.+/)?route\.jsx?$")
COMPONENT_RE = re.compile(r"^components/[^/]+\.jsx?$")
LIB_RE = re.compile(r"^lib/[^/]+\.js$")


IMPURE_RE = re.compile(
    r"""\bfetch\s*\(|from\s+['"]next/navigation['"]|from\s+['"]@/lib/"""
    r"""|\buse(?:State|Effect|Reducer|Context|Router|Session)\s*\(""")


MODULE_SIDE_EFFECT_RE = re.compile(
    r"^(?:await\s|(?:const|let|var)\s+\w+\s*=\s*(?:await\s|new\s+MongoClient)"
    r"|\w+\s*=\s*new\s+MongoClient|.*\.connect\s*\(\s*\)\s*$)", re.M)


@dataclass
class TestTarget:
    """One source file worth testing, and where its test will live."""
    path: str
    test_path: str
    tier: int
    phase: int = 0
    reason: str = ""

    @property
    def is_route(self) -> bool:
        return self.tier == TIER_ROUTE


@dataclass
class TestFailure:
    """One failing case, mapped back to the app file it is about."""
    test_file: str
    target: str
    name: str
    message: str
    stack: str = ""
    kind: str = "ASSERTION"
    stale: bool = False

    dom: str = ""

    hint: str = ""


@dataclass
class QAReport:
    targets: list = field(default_factory=list)
    written: list = field(default_factory=list)
    passed: int = 0
    failures: list = field(default_factory=list)
    quarantined: list = field(default_factory=list)

    unresolved: list = field(default_factory=list)
    suspects: list = field(default_factory=list)
    skipped_reason: str = ""

    def has_tests(self) -> bool:
        return bool(self.written)

    def is_clean(self) -> bool:
        """True only when nothing was left red, skipped, or set aside."""
        return not (self.failures or self.unresolved or self.quarantined)


def _stem(rel: str) -> str:
    return re.sub(r"\.jsx?$", "", rel)


def test_path_for(rel: str) -> str:
    """Where the test for `rel` lives."""
    ext = ".test.jsx" if rel.endswith(".jsx") else ".test.js"
    if ROUTE_RE.match(rel):

        inner = rel[len("app/"):].rsplit("/", 1)[0]
        if inner.startswith("api/"):
            inner = inner[len("api/"):]
        name = inner.replace("/", "_").replace("[", "").replace("]", "") or "root"
        return f"tests/unit/api/{name}{ext}"
    if COMPONENT_RE.match(rel):
        return f"tests/unit/components/{Path(rel).stem}{ext}"
    return f"tests/unit/lib/{Path(rel).stem}{ext}"


def _classify(rel: str, body: str) -> tuple:
    """(tier, reason) for a file, or (None, why not)."""
    if rel in GENERATED or rel in UNTESTABLE_LIB:
        return None, "generated by AgentForge — not the model's to fix"

    if ROUTE_RE.match(rel):
        if rel.startswith("app/api/auth/"):
            return None, "Better Auth's own handler — one re-export line"
        if "export" not in body:
            return None, "no exports"
        return TIER_ROUTE, "route handler: mockable, branch-rich"

    if rel.startswith("app/"):

        return None, "async Server Component — Vitest cannot render it (E2E only)"

    if COMPONENT_RE.match(rel):
        if "export default" not in body:
            return None, "no default export"
        if IMPURE_RE.search(body):
            return TIER_INTERACTIVE, "client component: needs fetch/router stubs"
        return TIER_PURE_COMPONENT, "pure component: props in, JSX out"

    if LIB_RE.match(rel):
        if MODULE_SIDE_EFFECT_RE.search(body):
            return None, "module-scope side effect — importing it does work"
        if "export" not in body:
            return None, "no exports"
        return TIER_PURE_LIB, "plain module"

    return None, "not a testable role"


def select_targets(paths, read, *, phase: int = 0, already: int = 0,
                   protected=None, limit: int = 0) -> list:
    """The subset of `paths` worth testing, best first, capped."""
    protected = frozenset(protected or ()) | GENERATED
    room = max(0, MAX_PER_PROJECT - already)
    if not room:
        return []

    scored, seen = [], set()
    for rel in paths:
        rel = (rel or "").strip().lstrip("./").replace("\\", "/")
        if not rel or rel in seen:
            continue
        seen.add(rel)
        if rel in protected:
            continue
        if not rel.endswith((".js", ".jsx")):
            continue
        try:
            body = read(rel)
        except Exception as e:
            log.debug(f"select_targets: cannot read {rel}: {e}")
            continue
        if not body:
            continue
        tier, why = _classify(rel, body)
        if tier is None:
            log.debug(f"select_targets: skip {rel} — {why}")
            continue
        scored.append(TestTarget(path=rel, test_path=test_path_for(rel),
                                 tier=tier, phase=phase, reason=why))

    scored.sort(key=lambda t: (t.tier, t.path))

    return scored[:min(limit or MAX_PER_PHASE, room)]
