"""Domain catalog entries."""
from __future__ import annotations

from .domains_core import GUEST_ROLE, SUPER_ADMIN, f, fk, pk, status, timestamps

DOMAIN_PART_A = {
    "hotel": {
        "label": "Hospitality SaaS",
        "system_category": "Hotel Management and Booking Web Application",
        "app_type_primary": "Hotel Management System with Booking Portal and Admin Dashboard",
        "keywords": ["hotel", "room", "booking", "guest", "reservation", "hospitality",
                     "check-in", "checkout", "stay", "resort", "lodge", "suite", "occupancy"],
        "roles": [SUPER_ADMIN,
                  {"role_key": "admin", "role_name": "Hotel Admin", "description": "Manages property, rooms, rates, staff, and settings."},
                  {"role_key": "front_desk", "role_name": "Front Desk", "description": "Handles check-in, check-out, walk-ins, and guest requests."},
                  {"role_key": "housekeeping", "role_name": "Housekeeping", "description": "Updates room cleaning status and maintenance flags."},
                  {"role_key": "guest_user", "role_name": "Guest", "description": "Searches rooms, books stays, pays online, and manages reservations."},
                  GUEST_ROLE],
        "modules": ["Public Website", "Authentication", "Room & Inventory Management",
                    "Booking Engine", "Front Desk Operations", "Housekeeping",
                    "Payments & Invoicing", "Guest Management", "Reviews & Ratings",
                    "Reports & Analytics", "Notifications", "Settings"],
        "tables": [
            {"table_name": "room_types", "description": "Categories of rooms with base rate and capacity.",
             "fields": [pk(), f("name", "string", nullable=False), f("description", "text", nullable=True),
                        f("base_rate", "decimal", nullable=False), f("max_occupancy", "integer", default=2),
                        f("amenities", "json", nullable=True), status(["active", "inactive"], "active")]},
            {"table_name": "rooms", "description": "Physical rooms belonging to a room type.",
             "fields": [pk(), fk("room_type_id", "room_types.id"), f("room_number", "string", unique=True),
                        f("floor", "integer", nullable=True),
                        f("housekeeping_status", "enum", values=["clean", "dirty", "inspected", "out_of_service"], default="clean"),
                        status(["available", "occupied", "maintenance"], "available")]},
            {"table_name": "bookings", "description": "Guest reservations across stay dates.",
             "fields": [pk(), f("booking_reference", "string", unique=True), fk("guest_id", "users.id", nullable=True),
                        fk("room_id", "rooms.id", nullable=True), fk("room_type_id", "room_types.id"),
                        f("check_in", "date", nullable=False), f("check_out", "date", nullable=False),
                        f("adults", "integer", default=1), f("children", "integer", default=0),
                        f("total_amount", "decimal"), f("source", "enum", values=["website", "walk_in", "phone", "ota"], default="website"),
                        status(["pending", "confirmed", "checked_in", "checked_out", "cancelled", "no_show"], "pending")]},
            {"table_name": "rate_plans", "description": "Seasonal / promotional pricing for room types.",
             "fields": [pk(), fk("room_type_id", "room_types.id"), f("name", "string"),
                        f("price", "decimal"), f("start_date", "date"), f("end_date", "date"),
                        f("min_nights", "integer", default=1)]},
            {"table_name": "payments", "description": "Payments and refunds against bookings.",
             "fields": [pk(), fk("booking_id", "bookings.id"), f("amount", "decimal"),
                        f("method", "enum", values=["card", "cash", "bank_transfer", "online_gateway"]),
                        f("transaction_reference", "string", nullable=True),
                        status(["pending", "paid", "failed", "refunded"], "pending"), f("paid_at", "datetime", nullable=True)]},
            {"table_name": "reviews", "description": "Guest reviews after checkout.",
             "fields": [pk(), fk("booking_id", "bookings.id"), fk("guest_id", "users.id"),
                        f("rating", "integer"), f("comment", "text", nullable=True), f("created_at", "datetime")]},
        ],
        "relationships": [
            {"from": "room_types.id", "to": "rooms.room_type_id", "type": "one_to_many", "description": "A room type has many rooms."},
            {"from": "rooms.id", "to": "bookings.room_id", "type": "one_to_many", "description": "A room can have many bookings over time."},
            {"from": "bookings.id", "to": "payments.booking_id", "type": "one_to_many", "description": "A booking can have many payments/refunds."},
            {"from": "bookings.id", "to": "reviews.booking_id", "type": "one_to_one", "description": "A completed booking can have one review."},
        ],
        "public_pages": [
            {"page_name": "Home", "route": "/", "sections": ["Hero with search (dates, guests)", "Featured room types", "Amenities", "Gallery", "Guest reviews", "Location map", "Footer"]},
            {"page_name": "Rooms", "route": "/rooms", "sections": ["Room type list", "Filters (price, occupancy, amenities)", "Availability calendar"]},
            {"page_name": "Room Details", "route": "/rooms/[id]", "sections": ["Photos", "Amenities", "Rate plans", "Book now"]},
            {"page_name": "Contact", "route": "/contact", "sections": ["Inquiry form", "Map", "Phone/email"]},
        ],
        "protected_pages": [
            {"page_name": "Guest Dashboard", "route": "/account", "page_type": "portal", "allowed_roles": ["guest_user"], "functions": ["View bookings", "Modify/cancel booking", "Download invoice", "Leave review"]},
            {"page_name": "Front Desk", "route": "/desk", "page_type": "dashboard", "allowed_roles": ["front_desk", "admin", "super_admin"], "functions": ["Check-in", "Check-out", "Create walk-in booking", "Assign room", "Take payment"]},
            {"page_name": "Housekeeping Board", "route": "/housekeeping", "page_type": "dashboard", "allowed_roles": ["housekeeping", "admin"], "functions": ["View room status", "Mark clean/dirty", "Flag maintenance"]},
            {"page_name": "Rooms & Rates", "route": "/admin/rooms", "page_type": "dashboard", "allowed_roles": ["admin", "super_admin"], "functions": ["Manage room types", "Manage rooms", "Manage rate plans"]},
            {"page_name": "Reports", "route": "/admin/reports", "page_type": "dashboard", "allowed_roles": ["admin", "super_admin"], "functions": ["Occupancy", "Revenue (ADR/RevPAR)", "Booking source mix"]},
        ],
        "workflows": [
            {"workflow_name": "Online Booking Workflow", "steps": ["Guest searches by dates and occupancy", "System shows available room types and rates", "Guest selects room type and rate plan", "Guest enters details and pays online", "System creates confirmed booking", "System emails confirmation and invoice", "Front desk sees upcoming arrival"]},
            {"workflow_name": "Check-in / Check-out Workflow", "steps": ["Front desk opens arrival", "Front desk verifies ID and assigns room", "System marks booking checked_in and room occupied", "On departure front desk records charges", "System marks checked_out and room dirty", "Housekeeping is notified to clean room"]},
        ],
        "notifications": [
            {"event": "Booking Confirmed", "recipients": ["guest_user"], "channels": ["email", "in_app"]},
            {"event": "Upcoming Arrival", "recipients": ["front_desk"], "channels": ["in_app", "email"]},
            {"event": "Payment Received", "recipients": ["guest_user", "admin"], "channels": ["email", "in_app"]},
            {"event": "Room Needs Cleaning", "recipients": ["housekeeping"], "channels": ["in_app"]},
        ],
        "reports": [
            {"report_name": "Occupancy Report", "filters": ["date range", "room type"], "exports": ["PDF", "Excel"]},
            {"report_name": "Revenue Report", "filters": ["date range", "source", "room type"], "exports": ["PDF", "Excel"]},
        ],
        "integrations": [
            {"name": "Payment Gateway", "type": "payment", "description": "Online card payments for bookings.", "required": False},
            {"name": "Channel Manager / OTA", "type": "distribution", "description": "Sync availability with OTAs (Booking.com, Expedia).", "required": False},
        ],
        "feature_options": ["Online booking & payments", "Front desk check-in/out", "Housekeeping board",
                            "Channel manager / OTA sync", "Loyalty programme", "Reviews & ratings",
                            "Multi-property support", "Dynamic / seasonal pricing"],
        "nfr_focus": ["Prevent double-booking of the same room/date (concurrency control)",
                      "Online payments must be PCI-DSS compliant via a hosted gateway"],
        "risks": [
            {"area": "Bookings", "risk": "Concurrent Bookings", "severity": "Medium", "reason": "Race conditions on the same room/date.", "mitigation": "Optimistic locking + idempotent reservation creation."},
            {"area": "Payments", "risk": "Payment Processing", "severity": "High", "reason": "PCI-DSS compliance complexity.", "mitigation": "Use a hosted checkout (Stripe/PayHere) to reduce scope."},
        ],
    },

    "retail": {
        "label": "Retail / POS",
        "system_category": "Retail POS, Inventory and E-commerce Web Application",
        "app_type_primary": "Retail POS with Inventory, E-commerce and Admin Dashboard",
        "keywords": ["retail", "pos", "point of sale", "inventory", "stock", "product", "sku",
                     "cashier", "store", "warehouse", "supplier", "barcode", "ecommerce", "shop", "cart", "checkout"],
        "roles": [SUPER_ADMIN,
                  {"role_key": "store_manager", "role_name": "Store Manager", "description": "Manages store inventory, pricing, staff, and reports."},
                  {"role_key": "cashier", "role_name": "Cashier", "description": "Operates the POS, scans products, and takes payments."},
                  {"role_key": "inventory_clerk", "role_name": "Inventory Clerk", "description": "Receives stock, adjusts quantities, and manages suppliers."},
                  {"role_key": "customer", "role_name": "Customer", "description": "Browses the online store, places orders, and tracks delivery."},
                  GUEST_ROLE],
        "modules": ["Public Storefront", "Authentication", "Product Catalog", "Inventory Management",
                    "Point of Sale (POS)", "Orders & Cart", "Suppliers & Purchasing",
                    "Payments", "Customers & Loyalty", "Reports & Analytics", "Notifications", "Settings"],
        "tables": [
            {"table_name": "categories", "description": "Product categories / departments.",
             "fields": [pk(), f("name", "string"), fk("parent_id", "categories.id", nullable=True), status(["active", "inactive"], "active")]},
            {"table_name": "products", "description": "Sellable products / SKUs.",
             "fields": [pk(), f("sku", "string", unique=True), f("name", "string", nullable=False),
                        fk("category_id", "categories.id", nullable=True), f("barcode", "string", nullable=True),
                        f("cost_price", "decimal"), f("sell_price", "decimal"), f("tax_rate", "decimal", default=0),
                        f("reorder_level", "integer", default=5), status(["active", "discontinued"], "active")]},
            {"table_name": "inventory", "description": "Per-warehouse stock levels.",
             "fields": [pk(), fk("product_id", "products.id"), fk("warehouse_id", "warehouses.id"),
                        f("quantity_on_hand", "integer", default=0), f("quantity_reserved", "integer", default=0)]},
            {"table_name": "warehouses", "description": "Stores / stock locations.",
             "fields": [pk(), f("name", "string"), f("location", "string", nullable=True), status(["active", "inactive"], "active")]},
            {"table_name": "sales_orders", "description": "POS + online sales transactions.",
             "fields": [pk(), f("order_number", "string", unique=True), fk("customer_id", "users.id", nullable=True),
                        fk("cashier_id", "users.id", nullable=True), f("channel", "enum", values=["pos", "online"], default="pos"),
                        f("subtotal", "decimal"), f("tax_total", "decimal", default=0), f("discount_total", "decimal", default=0),
                        f("grand_total", "decimal"), status(["draft", "paid", "fulfilled", "refunded", "cancelled"], "draft"), f("created_at", "datetime")]},
            {"table_name": "sales_order_items", "description": "Line items of a sale.",
             "fields": [pk(), fk("sales_order_id", "sales_orders.id"), fk("product_id", "products.id"),
                        f("quantity", "integer"), f("unit_price", "decimal"), f("line_total", "decimal")]},
            {"table_name": "suppliers", "description": "Vendors for purchasing stock.",
             "fields": [pk(), f("name", "string"), f("email", "string", nullable=True), f("phone", "string", nullable=True), status(["active", "inactive"], "active")]},
            {"table_name": "purchase_orders", "description": "Restock orders to suppliers.",
             "fields": [pk(), f("po_number", "string", unique=True), fk("supplier_id", "suppliers.id"),
                        f("total_amount", "decimal"), status(["draft", "ordered", "received", "cancelled"], "draft"), f("created_at", "datetime")]},
        ],
        "relationships": [
            {"from": "categories.id", "to": "products.category_id", "type": "one_to_many", "description": "A category has many products."},
            {"from": "products.id", "to": "inventory.product_id", "type": "one_to_many", "description": "A product has stock across warehouses."},
            {"from": "sales_orders.id", "to": "sales_order_items.sales_order_id", "type": "one_to_many", "description": "A sale has many line items."},
            {"from": "suppliers.id", "to": "purchase_orders.supplier_id", "type": "one_to_many", "description": "A supplier receives many purchase orders."},
        ],
        "public_pages": [
            {"page_name": "Storefront Home", "route": "/", "sections": ["Hero", "Featured products", "Categories", "Promotions", "Footer"]},
            {"page_name": "Shop", "route": "/shop", "sections": ["Product grid", "Filters (category, price)", "Search", "Add to cart"]},
            {"page_name": "Product Details", "route": "/product/[sku]", "sections": ["Gallery", "Price/stock", "Add to cart", "Related products"]},
            {"page_name": "Cart & Checkout", "route": "/checkout", "sections": ["Cart summary", "Address", "Payment", "Place order"]},
        ],
        "protected_pages": [
            {"page_name": "POS Terminal", "route": "/pos", "page_type": "pos", "allowed_roles": ["cashier", "store_manager", "super_admin"], "functions": ["Scan/search product", "Add to ticket", "Apply discount", "Take payment", "Print receipt", "Open/close till"]},
            {"page_name": "Inventory", "route": "/admin/inventory", "page_type": "dashboard", "allowed_roles": ["inventory_clerk", "store_manager", "super_admin"], "functions": ["Receive stock", "Stock adjustments", "Low-stock alerts", "Stock transfer"]},
            {"page_name": "Products", "route": "/admin/products", "page_type": "dashboard", "allowed_roles": ["store_manager", "super_admin"], "functions": ["Create/edit product", "Manage categories", "Manage pricing & tax"]},
            {"page_name": "Purchasing", "route": "/admin/purchasing", "page_type": "dashboard", "allowed_roles": ["store_manager", "super_admin"], "functions": ["Manage suppliers", "Create purchase orders", "Receive PO"]},
            {"page_name": "Reports", "route": "/admin/reports", "page_type": "dashboard", "allowed_roles": ["store_manager", "super_admin"], "functions": ["Sales by day/product", "Inventory valuation", "Profit margin"]},
        ],
        "workflows": [
            {"workflow_name": "POS Sale Workflow", "steps": ["Cashier scans products into a ticket", "System prices items and applies tax/discounts", "Cashier selects payment method", "Customer pays (cash/card)", "System decrements inventory", "System prints receipt and records the sale"]},
            {"workflow_name": "Stock Replenishment Workflow", "steps": ["System flags products below reorder level", "Manager creates a purchase order to a supplier", "Supplier ships goods", "Clerk receives stock against the PO", "System increases quantity on hand", "Low-stock alert clears"]},
        ],
        "notifications": [
            {"event": "Low Stock", "recipients": ["inventory_clerk", "store_manager"], "channels": ["in_app", "email"]},
            {"event": "Order Placed (Online)", "recipients": ["customer", "store_manager"], "channels": ["email", "in_app"]},
            {"event": "Refund Issued", "recipients": ["customer", "store_manager"], "channels": ["email"]},
        ],
        "reports": [
            {"report_name": "Sales Report", "filters": ["date range", "channel", "cashier", "product"], "exports": ["PDF", "Excel"]},
            {"report_name": "Inventory Valuation", "filters": ["warehouse", "category"], "exports": ["PDF", "Excel"]},
        ],
        "integrations": [
            {"name": "Payment Gateway", "type": "payment", "description": "Card payments for POS and online checkout.", "required": False},
            {"name": "Barcode Scanner", "type": "hardware", "description": "USB/Bluetooth barcode scanning at POS.", "required": False},
            {"name": "Receipt Printer", "type": "hardware", "description": "Thermal receipt printing.", "required": False},
        ],
        "feature_options": ["In-store POS", "Online storefront", "Barcode scanning", "Multi-warehouse stock",
                            "Supplier purchase orders", "Loyalty points", "Discounts & promotions", "Tax management"],
        "nfr_focus": ["POS must keep working briefly offline and sync when reconnected",
                      "Inventory decrements must be atomic to avoid overselling"],
        "risks": [
            {"area": "Inventory", "risk": "Overselling", "severity": "High", "reason": "Concurrent POS + online sales of last unit.", "mitigation": "Atomic stock decrement with reservation + transaction."},
            {"area": "POS", "risk": "Offline Resilience", "severity": "Medium", "reason": "Network drops at the till stop sales.", "mitigation": "Local queue with sync on reconnect."},
        ],
    },

    "school": {
        "label": "Education / LMS",
        "system_category": "School Management, LMS, Fees and Transport Web Application",
        "app_type_primary": "School Management System and LMS with Parent Portal and Admin Dashboard",
        "keywords": ["school", "student", "class", "teacher", "lms", "education", "exam", "attendance",
                     "parent", "fees", "tuition", "course", "lesson", "grade", "academic", "transport", "library"],
        "roles": [SUPER_ADMIN,
                  {"role_key": "admin", "role_name": "School Admin", "description": "Manages school setup, users, classes, fees, and configuration."},
                  {"role_key": "teacher", "role_name": "Teacher", "description": "Manages lessons, attendance, assignments, and marks."},
                  {"role_key": "student", "role_name": "Student", "description": "Views lessons, submits assignments, and views results."},
                  {"role_key": "parent", "role_name": "Parent", "description": "Views child attendance, marks, fees, and pays online."},
                  {"role_key": "accountant", "role_name": "Accountant", "description": "Manages fee invoices, payments, and financial reports."},
                  GUEST_ROLE],
        "modules": ["Public Website", "Authentication", "Admission Management", "Student Management",
                    "Class & Subject Management", "Attendance", "LMS (Lessons & Assignments)",
                    "Exams & Grading", "Fee Management", "Transport Management", "Parent Portal",
                    "Reports & Analytics", "Notifications", "Settings"],
        "tables": [
            {"table_name": "classes", "description": "Grades / classes such as Grade 6.",
             "fields": [pk(), f("class_name", "string"), f("class_level", "integer", nullable=True), status(["active", "inactive"], "active")]},
            {"table_name": "sections", "description": "Sections within a class (6-A, 6-B).",
             "fields": [pk(), fk("class_id", "classes.id"), f("section_name", "string"), fk("class_teacher_id", "users.id", nullable=True), f("capacity", "integer", nullable=True)]},
            {"table_name": "subjects", "description": "Subjects taught at the school.",
             "fields": [pk(), f("subject_code", "string", unique=True), f("subject_name", "string"), status(["active", "inactive"], "active")]},
            {"table_name": "students", "description": "Student profiles.",
             "fields": [pk(), fk("user_id", "users.id", nullable=True), f("admission_number", "string", unique=True),
                        f("full_name", "string"), f("date_of_birth", "date", nullable=True), fk("class_id", "classes.id"),
                        fk("section_id", "sections.id"), status(["active", "graduated", "transferred"], "active")]},
            {"table_name": "attendance_records", "description": "Daily attendance.",
             "fields": [pk(), fk("student_id", "students.id"), f("attendance_date", "date"),
                        f("status", "enum", values=["present", "absent", "late", "excused"]), fk("marked_by", "users.id")]},
            {"table_name": "assignments", "description": "LMS assignments.",
             "fields": [pk(), f("title", "string"), fk("subject_id", "subjects.id"), fk("teacher_id", "users.id"),
                        f("due_date", "datetime"), f("total_marks", "decimal", default=100), status(["draft", "published", "closed"], "draft")]},
            {"table_name": "exam_results", "description": "Student marks per subject.",
             "fields": [pk(), fk("student_id", "students.id"), fk("subject_id", "subjects.id"),
                        f("marks_obtained", "decimal"), f("total_marks", "decimal", default=100), f("grade", "string", nullable=True)]},
            {"table_name": "fee_invoices", "description": "Student fee invoices.",
             "fields": [pk(), f("invoice_number", "string", unique=True), fk("student_id", "students.id"),
                        f("fee_type", "enum", values=["admission", "tuition", "exam", "transport", "other"]),
                        f("grand_total", "decimal"), f("paid_amount", "decimal", default=0),
                        f("payment_status", "enum", values=["unpaid", "partial", "paid"], default="unpaid"), f("due_date", "date")]},
            {"table_name": "transport_routes", "description": "School bus routes.",
             "fields": [pk(), f("route_name", "string"), f("monthly_fee", "decimal", default=0), status(["active", "inactive"], "active")]},
        ],
        "relationships": [
            {"from": "classes.id", "to": "sections.class_id", "type": "one_to_many", "description": "A class has many sections."},
            {"from": "sections.id", "to": "students.section_id", "type": "one_to_many", "description": "A section has many students."},
            {"from": "students.id", "to": "attendance_records.student_id", "type": "one_to_many", "description": "A student has many attendance records."},
            {"from": "students.id", "to": "fee_invoices.student_id", "type": "one_to_many", "description": "A student has many fee invoices."},
        ],
        "public_pages": [
            {"page_name": "Home", "route": "/", "sections": ["Hero + admission CTA", "Programs", "Why choose us", "Notices", "Footer"]},
            {"page_name": "Admissions", "route": "/admissions", "sections": ["Process", "Required documents", "Inquiry form", "FAQ"]},
            {"page_name": "Academics", "route": "/academics", "sections": ["Curriculum", "Streams", "Calendar"]},
            {"page_name": "Contact", "route": "/contact", "sections": ["Form", "Map", "Phone/email"]},
        ],
        "protected_pages": [
            {"page_name": "Student Dashboard", "route": "/student", "page_type": "portal", "allowed_roles": ["student"], "functions": ["View timetable", "View lessons", "Submit assignments", "View results", "View fees"]},
            {"page_name": "Parent Dashboard", "route": "/parent", "page_type": "portal", "allowed_roles": ["parent"], "functions": ["View child attendance/marks", "View & pay fees", "View notices", "Contact teacher"]},
            {"page_name": "Teacher Dashboard", "route": "/teacher", "page_type": "dashboard", "allowed_roles": ["teacher"], "functions": ["Mark attendance", "Create lessons/assignments", "Grade submissions", "Enter exam marks"]},
            {"page_name": "Fee Management", "route": "/admin/fees", "page_type": "dashboard", "allowed_roles": ["accountant", "admin", "super_admin"], "functions": ["Generate invoices", "Record payments", "Print receipts", "Fee reports"]},
            {"page_name": "Admin Dashboard", "route": "/admin", "page_type": "dashboard", "allowed_roles": ["admin", "super_admin"], "functions": ["Manage students/teachers", "Manage classes/subjects", "Manage transport", "Reports"]},
        ],
        "workflows": [
            {"workflow_name": "Daily Attendance Workflow", "steps": ["Teacher selects class/section", "System lists students", "Teacher marks present/absent/late", "System saves records", "System notifies parents of absentees", "Attendance report updates"]},
            {"workflow_name": "Fee Payment Workflow", "steps": ["Accountant generates invoice", "Parent views invoice in portal", "Parent pays online or school records manual payment", "System updates payment status", "System generates receipt", "Fee report updates"]},
        ],
        "notifications": [
            {"event": "Student Absent", "recipients": ["parent"], "channels": ["sms", "email", "in_app"]},
            {"event": "Exam Result Published", "recipients": ["student", "parent"], "channels": ["email", "in_app"]},
            {"event": "Fee Invoice Created", "recipients": ["parent"], "channels": ["email", "in_app"]},
        ],
        "reports": [
            {"report_name": "Attendance Report", "filters": ["date range", "class", "section"], "exports": ["PDF", "Excel"]},
            {"report_name": "Fee Collection Report", "filters": ["date range", "class", "status"], "exports": ["PDF", "Excel"]},
            {"report_name": "Exam Result Report", "filters": ["exam", "class", "subject"], "exports": ["PDF", "Excel"]},
        ],
        "integrations": [
            {"name": "Payment Gateway", "type": "payment", "description": "Online fee payments for parents.", "required": False},
            {"name": "SMS Gateway", "type": "messaging", "description": "Absence + result SMS alerts.", "required": False},
        ],
        "feature_options": ["Online admissions", "Attendance", "LMS lessons & assignments", "Exams & grading",
                            "Fee management & online payment", "Transport management", "Parent portal", "Library"],
        "nfr_focus": ["Students/parents must only access their own records",
                      "Marks and fee changes must be recorded in audit logs"],
        "risks": [
            {"area": "Privacy", "risk": "Cross-student data leakage", "severity": "High", "reason": "A parent could view another child's data.", "mitigation": "Strict row-level authorization on every query."},
            {"area": "Fees", "risk": "Payment reconciliation", "severity": "Medium", "reason": "Online + manual payments can desync.", "mitigation": "Idempotent webhooks + daily reconciliation report."},
        ],
    },

}
