"""Domain catalog entries."""
from __future__ import annotations

from .domains_core import GUEST_ROLE, SUPER_ADMIN, f, fk, pk, status, timestamps

DOMAIN_PART_B = {
    "vehicle": {
        "label": "Automotive Platform",
        "system_category": "Vehicle Sales, Rental, Service and Spare Parts Web Application",
        "app_type_primary": "Vehicle Sales / Rental / Service Center with Admin Dashboard",
        "keywords": ["vehicle", "car", "auto", "automobile", "dealership", "rental", "service center",
                     "spare parts", "garage", "mechanic", "fleet", "test drive", "motorbike", "showroom"],
        "roles": [SUPER_ADMIN,
                  {"role_key": "admin", "role_name": "Dealership Admin", "description": "Manages inventory, staff, pricing, and settings."},
                  {"role_key": "sales_agent", "role_name": "Sales Agent", "description": "Handles leads, test drives, quotes, and sales."},
                  {"role_key": "service_advisor", "role_name": "Service Advisor", "description": "Manages service bookings, jobs, and parts."},
                  {"role_key": "customer", "role_name": "Customer", "description": "Browses vehicles, books test drives/service, and rents vehicles."},
                  GUEST_ROLE],
        "modules": ["Public Website", "Authentication", "Vehicle Inventory", "Sales & Leads",
                    "Rental Management", "Service & Workshop", "Spare Parts (POS)", "Payments",
                    "Customers", "Reports & Analytics", "Notifications", "Settings"],
        "tables": [
            {"table_name": "vehicles", "description": "Vehicles for sale or rent.",
             "fields": [pk(), f("vin", "string", unique=True), f("make", "string"), f("model", "string"),
                        f("year", "integer"), f("mileage", "integer", nullable=True), f("price", "decimal"),
                        f("listing_type", "enum", values=["sale", "rental", "both"], default="sale"),
                        status(["available", "reserved", "sold", "rented", "in_service"], "available")]},
            {"table_name": "leads", "description": "Sales leads and inquiries.",
             "fields": [pk(), fk("vehicle_id", "vehicles.id", nullable=True), fk("customer_id", "users.id", nullable=True),
                        f("source", "enum", values=["website", "walk_in", "phone", "referral"], default="website"),
                        status(["new", "contacted", "test_drive", "negotiating", "won", "lost"], "new"), f("created_at", "datetime")]},
            {"table_name": "sales_orders", "description": "Vehicle sales transactions.",
             "fields": [pk(), f("order_number", "string", unique=True), fk("vehicle_id", "vehicles.id"),
                        fk("customer_id", "users.id"), fk("sales_agent_id", "users.id"), f("sale_price", "decimal"),
                        status(["quoted", "deposit_paid", "completed", "cancelled"], "quoted"), f("created_at", "datetime")]},
            {"table_name": "rentals", "description": "Vehicle rental agreements.",
             "fields": [pk(), fk("vehicle_id", "vehicles.id"), fk("customer_id", "users.id"),
                        f("start_date", "date"), f("end_date", "date"), f("daily_rate", "decimal"),
                        f("total_amount", "decimal"), status(["booked", "active", "returned", "cancelled"], "booked")]},
            {"table_name": "service_jobs", "description": "Workshop service jobs.",
             "fields": [pk(), f("job_number", "string", unique=True), fk("vehicle_id", "vehicles.id", nullable=True),
                        fk("customer_id", "users.id"), fk("service_advisor_id", "users.id", nullable=True),
                        f("description", "text"), f("scheduled_at", "datetime", nullable=True),
                        f("total_cost", "decimal", default=0), status(["booked", "in_progress", "ready", "completed", "cancelled"], "booked")]},
            {"table_name": "parts", "description": "Spare parts inventory.",
             "fields": [pk(), f("part_number", "string", unique=True), f("name", "string"),
                        f("price", "decimal"), f("quantity_on_hand", "integer", default=0), f("reorder_level", "integer", default=3)]},
        ],
        "relationships": [
            {"from": "vehicles.id", "to": "leads.vehicle_id", "type": "one_to_many", "description": "A vehicle attracts many leads."},
            {"from": "vehicles.id", "to": "sales_orders.vehicle_id", "type": "one_to_one", "description": "A vehicle is sold once."},
            {"from": "vehicles.id", "to": "rentals.vehicle_id", "type": "one_to_many", "description": "A vehicle can be rented many times."},
            {"from": "service_jobs.id", "to": "parts.id", "type": "many_to_many", "via": "service_job_parts", "description": "Service jobs consume parts."},
        ],
        "public_pages": [
            {"page_name": "Home", "route": "/", "sections": ["Hero search", "Featured vehicles", "Sell/Rent/Service tabs", "Why us", "Footer"]},
            {"page_name": "Inventory", "route": "/vehicles", "sections": ["Vehicle grid", "Filters (make, model, year, price)", "Compare"]},
            {"page_name": "Vehicle Details", "route": "/vehicles/[id]", "sections": ["Gallery", "Specs", "Book test drive", "Enquire / Finance"]},
            {"page_name": "Book Service", "route": "/service", "sections": ["Service types", "Booking form", "Locations"]},
        ],
        "protected_pages": [
            {"page_name": "Customer Account", "route": "/account", "page_type": "portal", "allowed_roles": ["customer"], "functions": ["My enquiries", "My rentals", "My service jobs", "Invoices"]},
            {"page_name": "Sales CRM", "route": "/admin/sales", "page_type": "dashboard", "allowed_roles": ["sales_agent", "admin", "super_admin"], "functions": ["Manage leads", "Schedule test drives", "Create quotes", "Close sale"]},
            {"page_name": "Workshop", "route": "/admin/service", "page_type": "dashboard", "allowed_roles": ["service_advisor", "admin", "super_admin"], "functions": ["Manage service jobs", "Assign mechanics", "Add parts/labour", "Invoice"]},
            {"page_name": "Inventory", "route": "/admin/vehicles", "page_type": "dashboard", "allowed_roles": ["admin", "super_admin"], "functions": ["Add/edit vehicles", "Manage rental fleet", "Pricing"]},
            {"page_name": "Reports", "route": "/admin/reports", "page_type": "dashboard", "allowed_roles": ["admin", "super_admin"], "functions": ["Sales pipeline", "Rental utilization", "Service revenue"]},
        ],
        "workflows": [
            {"workflow_name": "Vehicle Sales Workflow", "steps": ["Customer enquires on a vehicle", "Sales agent contacts and books a test drive", "Agent prepares a quote", "Customer pays deposit", "Paperwork and financing completed", "Vehicle marked sold and invoice issued"]},
            {"workflow_name": "Service Booking Workflow", "steps": ["Customer books a service slot", "Service advisor creates a job card", "Mechanic performs work and adds parts/labour", "Advisor reviews and prices the job", "Customer pays and collects the vehicle", "Job marked completed"]},
        ],
        "notifications": [
            {"event": "New Lead", "recipients": ["sales_agent"], "channels": ["in_app", "email"]},
            {"event": "Test Drive Scheduled", "recipients": ["customer", "sales_agent"], "channels": ["email", "in_app"]},
            {"event": "Service Ready for Pickup", "recipients": ["customer"], "channels": ["sms", "email"]},
        ],
        "reports": [
            {"report_name": "Sales Pipeline", "filters": ["date range", "agent", "status"], "exports": ["PDF", "Excel"]},
            {"report_name": "Service Revenue", "filters": ["date range", "advisor"], "exports": ["PDF", "Excel"]},
        ],
        "integrations": [
            {"name": "Payment Gateway", "type": "payment", "description": "Deposits and service payments.", "required": False},
            {"name": "Finance / Leasing API", "type": "finance", "description": "Vehicle financing quotes.", "required": False},
        ],
        "feature_options": ["Vehicle sales CRM", "Rental management", "Service workshop", "Spare parts POS",
                            "Test drive booking", "Online enquiries", "Financing quotes", "Fleet tracking"],
        "nfr_focus": ["A vehicle must not be double-sold or double-booked across sales/rental/service"],
        "risks": [
            {"area": "Inventory", "risk": "Double allocation", "severity": "High", "reason": "Same vehicle sold and rented simultaneously.", "mitigation": "Single source-of-truth status with locking."},
        ],
    },

    "hospital": {
        "label": "Healthcare / Clinic",
        "system_category": "Hospital / Clinic Management Web Application",
        "app_type_primary": "Clinic Management with Appointments, EMR and Admin Dashboard",
        "keywords": ["hospital", "clinic", "patient", "doctor", "appointment", "healthcare", "medical",
                     "pharmacy", "diagnosis", "prescription", "emr", "nurse", "ward", "lab", "treatment"],
        "roles": [SUPER_ADMIN,
                  {"role_key": "admin", "role_name": "Clinic Admin", "description": "Manages staff, schedules, billing, and settings."},
                  {"role_key": "doctor", "role_name": "Doctor", "description": "Manages appointments, consultations, and prescriptions."},
                  {"role_key": "nurse", "role_name": "Nurse", "description": "Records vitals and assists consultations."},
                  {"role_key": "receptionist", "role_name": "Receptionist", "description": "Registers patients and books appointments."},
                  {"role_key": "patient", "role_name": "Patient", "description": "Books appointments and views records/prescriptions."},
                  GUEST_ROLE],
        "modules": ["Public Website", "Authentication", "Patient Management", "Appointments",
                    "Consultations / EMR", "Prescriptions", "Pharmacy & Billing", "Lab Tests",
                    "Reports & Analytics", "Notifications", "Settings"],
        "tables": [
            {"table_name": "patients", "description": "Patient demographic and medical profile.",
             "fields": [pk(), fk("user_id", "users.id", nullable=True), f("mrn", "string", unique=True),
                        f("full_name", "string"), f("date_of_birth", "date", nullable=True),
                        f("gender", "enum", values=["male", "female", "other"], nullable=True),
                        f("blood_group", "string", nullable=True), status(["active", "inactive"], "active")]},
            {"table_name": "doctors", "description": "Doctor profiles and specialties.",
             "fields": [pk(), fk("user_id", "users.id"), f("specialty", "string"), f("license_number", "string", unique=True),
                        f("consultation_fee", "decimal", default=0)]},
            {"table_name": "appointments", "description": "Patient appointments with doctors.",
             "fields": [pk(), fk("patient_id", "patients.id"), fk("doctor_id", "doctors.id"),
                        f("scheduled_at", "datetime"), f("reason", "text", nullable=True),
                        status(["booked", "confirmed", "in_consultation", "completed", "cancelled", "no_show"], "booked")]},
            {"table_name": "consultations", "description": "EMR consultation notes.",
             "fields": [pk(), fk("appointment_id", "appointments.id"), fk("patient_id", "patients.id"),
                        f("symptoms", "text", nullable=True), f("diagnosis", "text", nullable=True),
                        f("notes", "text", nullable=True), f("created_at", "datetime")]},
            {"table_name": "prescriptions", "description": "Medications prescribed during a consultation.",
             "fields": [pk(), fk("consultation_id", "consultations.id"), f("medication", "string"),
                        f("dosage", "string"), f("frequency", "string"), f("duration", "string")]},
            {"table_name": "invoices", "description": "Patient billing.",
             "fields": [pk(), f("invoice_number", "string", unique=True), fk("patient_id", "patients.id"),
                        f("total_amount", "decimal"), f("paid_amount", "decimal", default=0),
                        f("payment_status", "enum", values=["unpaid", "partial", "paid"], default="unpaid")]},
        ],
        "relationships": [
            {"from": "patients.id", "to": "appointments.patient_id", "type": "one_to_many", "description": "A patient has many appointments."},
            {"from": "doctors.id", "to": "appointments.doctor_id", "type": "one_to_many", "description": "A doctor has many appointments."},
            {"from": "appointments.id", "to": "consultations.appointment_id", "type": "one_to_one", "description": "An appointment yields one consultation."},
            {"from": "consultations.id", "to": "prescriptions.consultation_id", "type": "one_to_many", "description": "A consultation has many prescriptions."},
        ],
        "public_pages": [
            {"page_name": "Home", "route": "/", "sections": ["Hero + book appointment", "Specialties", "Doctors", "Footer"]},
            {"page_name": "Doctors", "route": "/doctors", "sections": ["Doctor list", "Filter by specialty", "Availability"]},
            {"page_name": "Book Appointment", "route": "/book", "sections": ["Select doctor/slot", "Patient details", "Confirm"]},
        ],
        "protected_pages": [
            {"page_name": "Patient Portal", "route": "/patient", "page_type": "portal", "allowed_roles": ["patient"], "functions": ["Book/cancel appointment", "View prescriptions", "View invoices", "Download records"]},
            {"page_name": "Doctor Console", "route": "/doctor", "page_type": "dashboard", "allowed_roles": ["doctor"], "functions": ["View schedule", "Start consultation", "Write diagnosis", "Prescribe"]},
            {"page_name": "Reception", "route": "/reception", "page_type": "dashboard", "allowed_roles": ["receptionist", "admin"], "functions": ["Register patient", "Book appointment", "Take payment"]},
            {"page_name": "Admin Dashboard", "route": "/admin", "page_type": "dashboard", "allowed_roles": ["admin", "super_admin"], "functions": ["Manage staff", "Schedules", "Billing", "Reports"]},
        ],
        "workflows": [
            {"workflow_name": "Appointment & Consultation Workflow", "steps": ["Patient books an appointment", "Receptionist confirms and collects details", "Nurse records vitals", "Doctor consults and records diagnosis", "Doctor issues prescription", "System bills the patient and updates records"]},
        ],
        "notifications": [
            {"event": "Appointment Confirmed", "recipients": ["patient"], "channels": ["email", "sms", "in_app"]},
            {"event": "Appointment Reminder", "recipients": ["patient"], "channels": ["sms", "in_app"]},
        ],
        "reports": [
            {"report_name": "Appointments Report", "filters": ["date range", "doctor", "status"], "exports": ["PDF", "Excel"]},
            {"report_name": "Revenue Report", "filters": ["date range", "doctor"], "exports": ["PDF", "Excel"]},
        ],
        "integrations": [
            {"name": "Payment Gateway", "type": "payment", "description": "Consultation/billing payments.", "required": False},
            {"name": "SMS Reminders", "type": "messaging", "description": "Appointment reminders.", "required": False},
        ],
        "feature_options": ["Online appointment booking", "Doctor consultation / EMR", "Prescriptions",
                            "Billing & invoices", "Lab tests", "Pharmacy", "Patient portal"],
        "nfr_focus": ["Patient medical records are sensitive and must be access-controlled and encrypted at rest",
                      "All record access must be audit-logged for compliance"],
        "risks": [
            {"area": "Compliance", "risk": "PHI exposure", "severity": "High", "reason": "Medical data is highly sensitive.", "mitigation": "Encryption at rest, strict RBAC, full audit trail."},
        ],
    },

    "restaurant": {
        "label": "Food & Restaurant",
        "system_category": "Online Food Ordering and Restaurant Management Web Application",
        "app_type_primary": "Food Ordering & Restaurant Management with Kitchen and Admin Dashboard",
        "keywords": ["restaurant", "food", "menu", "dish", "meal", "cuisine", "cafe", "kitchen",
                     "order", "ordering", "delivery", "takeaway", "dine", "dine-in", "table",
                     "reservation", "recipe", "pizza", "burger", "bakery", "catering", "waiter", "chef"],
        "roles": [SUPER_ADMIN,
                  {"role_key": "admin", "role_name": "Restaurant Admin", "description": "Manages menu, branches, staff, pricing, and settings."},
                  {"role_key": "manager", "role_name": "Manager", "description": "Oversees daily orders, staff, promotions, and views sales reports."},
                  {"role_key": "kitchen_staff", "role_name": "Kitchen Staff", "description": "Sees incoming orders on a live board and updates cooking status."},
                  {"role_key": "cashier", "role_name": "Cashier / Counter", "description": "Takes counter orders and processes payments."},
                  {"role_key": "delivery_driver", "role_name": "Delivery Driver", "description": "Receives assigned deliveries and updates delivery status."},
                  {"role_key": "customer", "role_name": "Customer", "description": "Browses the menu, orders (QR/online), pays, and tracks the order."},
                  GUEST_ROLE],
        "modules": ["Public Website", "Authentication", "Menu Management", "Online Ordering & Cart",
                    "Table QR Ordering", "Kitchen Display (KDS)", "Order Management", "Payments",
                    "Delivery Management", "Reservations", "Promotions & Loyalty",
                    "Reports & Analytics", "Notifications", "Settings"],
        "tables": [
            {"table_name": "menu_categories", "description": "Groups of menu items (Starters, Mains, Drinks).",
             "fields": [pk(), f("name", "string", nullable=False), f("display_order", "integer", default=0), status(["active", "inactive"], "active")]},
            {"table_name": "menu_items", "description": "Individual dishes/products on the menu.",
             "fields": [pk(), fk("category_id", "menu_categories.id"), f("name", "string", nullable=False),
                        f("description", "text", nullable=True), f("price", "decimal", nullable=False),
                        f("image_url", "string", nullable=True), f("is_veg", "boolean", default=False),
                        f("spice_level", "enum", values=["none", "mild", "medium", "hot"], default="none"),
                        f("prep_minutes", "integer", default=15), status(["available", "sold_out", "hidden"], "available")]},
            {"table_name": "item_modifiers", "description": "Add-ons / options for an item (extra cheese, size).",
             "fields": [pk(), fk("menu_item_id", "menu_items.id"), f("name", "string"), f("price_delta", "decimal", default=0),
                        f("group", "string", nullable=True), f("required", "boolean", default=False)]},
            {"table_name": "dining_tables", "description": "Physical tables with QR codes for in-restaurant ordering.",
             "fields": [pk(), f("table_number", "string", unique=True), f("seats", "integer", default=4),
                        f("qr_code", "string", unique=True), status(["free", "occupied", "reserved"], "free")]},
            {"table_name": "orders", "description": "Customer orders across channels.",
             "fields": [pk(), f("order_number", "string", unique=True), fk("customer_id", "users.id", nullable=True),
                        fk("dining_table_id", "dining_tables.id", nullable=True),
                        f("channel", "enum", values=["dine_in_qr", "online_delivery", "online_pickup", "counter"], default="online_delivery"),
                        f("subtotal", "decimal"), f("delivery_fee", "decimal", default=0), f("tax_total", "decimal", default=0),
                        f("tip", "decimal", default=0), f("grand_total", "decimal"), f("notes", "text", nullable=True),
                        f("status", "enum", values=["placed", "accepted", "preparing", "ready", "out_for_delivery", "completed", "cancelled"], default="placed"),
                        f("created_at", "datetime")]},
            {"table_name": "order_items", "description": "Line items within an order.",
             "fields": [pk(), fk("order_id", "orders.id"), fk("menu_item_id", "menu_items.id"),
                        f("quantity", "integer", default=1), f("unit_price", "decimal"),
                        f("selected_modifiers", "json", nullable=True), f("line_total", "decimal"), f("notes", "string", nullable=True)]},
            {"table_name": "payments", "description": "Payments against orders.",
             "fields": [pk(), fk("order_id", "orders.id"), f("amount", "decimal"),
                        f("method", "enum", values=["card", "cash", "online_gateway", "wallet"]),
                        f("transaction_reference", "string", nullable=True),
                        status(["pending", "paid", "failed", "refunded"], "pending"), f("paid_at", "datetime", nullable=True)]},
            {"table_name": "deliveries", "description": "Delivery assignments and tracking.",
             "fields": [pk(), fk("order_id", "orders.id"), fk("driver_id", "users.id", nullable=True),
                        f("address", "text"), f("lat", "decimal", nullable=True), f("lng", "decimal", nullable=True),
                        f("status", "enum", values=["assigned", "picked_up", "delivered", "failed"], default="assigned"),
                        f("eta_minutes", "integer", nullable=True)]},
            {"table_name": "reservations", "description": "Table reservations.",
             "fields": [pk(), fk("customer_id", "users.id", nullable=True), fk("dining_table_id", "dining_tables.id", nullable=True),
                        f("party_size", "integer"), f("reserved_at", "datetime"),
                        status(["booked", "seated", "completed", "cancelled", "no_show"], "booked")]},
            {"table_name": "promotions", "description": "Discounts, coupons, and loyalty offers.",
             "fields": [pk(), f("code", "string", unique=True), f("description", "string"),
                        f("discount_type", "enum", values=["percent", "amount", "free_item"]),
                        f("value", "decimal"), f("starts_at", "date", nullable=True), f("ends_at", "date", nullable=True),
                        status(["active", "expired", "disabled"], "active")]},
        ],
        "relationships": [
            {"from": "menu_categories.id", "to": "menu_items.category_id", "type": "one_to_many", "description": "A category has many menu items."},
            {"from": "menu_items.id", "to": "item_modifiers.menu_item_id", "type": "one_to_many", "description": "An item has many modifiers."},
            {"from": "orders.id", "to": "order_items.order_id", "type": "one_to_many", "description": "An order has many line items."},
            {"from": "menu_items.id", "to": "order_items.menu_item_id", "type": "one_to_many", "description": "A menu item appears in many order lines."},
            {"from": "orders.id", "to": "payments.order_id", "type": "one_to_many", "description": "An order can have payments/refunds."},
            {"from": "orders.id", "to": "deliveries.order_id", "type": "one_to_one", "description": "A delivery order has one delivery record."},
            {"from": "dining_tables.id", "to": "orders.dining_table_id", "type": "one_to_many", "description": "A table can have many QR orders over time."},
        ],
        "public_pages": [
            {"page_name": "Home", "route": "/", "sections": ["Hero with order CTA", "Featured dishes", "How it works", "Offers", "Reviews", "Location & hours", "Footer"]},
            {"page_name": "Menu", "route": "/menu", "sections": ["Category tabs", "Dish cards with photo/price", "Add to cart", "Search & filters (veg, spicy)"]},
            {"page_name": "Cart & Checkout", "route": "/checkout", "sections": ["Cart summary", "Delivery/pickup choice", "Address & time", "Payment", "Place order"]},
            {"page_name": "Track Order", "route": "/track/[order]", "sections": ["Live status timeline", "ETA", "Driver location"]},
            {"page_name": "Reserve a Table", "route": "/reserve", "sections": ["Date/time/party size", "Confirm reservation"]},
        ],
        "protected_pages": [
            {"page_name": "Customer Account", "route": "/account", "page_type": "portal", "allowed_roles": ["customer"], "functions": ["Order history", "Reorder", "Saved addresses", "Loyalty points", "My reservations"]},
            {"page_name": "Kitchen Display", "route": "/kds", "page_type": "dashboard", "allowed_roles": ["kitchen_staff", "manager", "admin"], "functions": ["See new orders live", "Accept order", "Mark preparing/ready", "Bump completed tickets"]},
            {"page_name": "Order Management", "route": "/admin/orders", "page_type": "dashboard", "allowed_roles": ["manager", "cashier", "admin", "super_admin"], "functions": ["View all orders", "Refund/cancel", "Assign driver", "Reprint receipt"]},
            {"page_name": "Menu Management", "route": "/admin/menu", "page_type": "dashboard", "allowed_roles": ["manager", "admin", "super_admin"], "functions": ["Create/edit items", "Manage categories & modifiers", "Set availability/sold-out", "Pricing"]},
            {"page_name": "Delivery Board", "route": "/admin/delivery", "page_type": "dashboard", "allowed_roles": ["manager", "delivery_driver", "admin"], "functions": ["Assign deliveries", "Update status", "Driver view of route"]},
            {"page_name": "Reports", "route": "/admin/reports", "page_type": "dashboard", "allowed_roles": ["manager", "admin", "super_admin"], "functions": ["Sales by day/item/channel", "Peak hours", "Average order value", "Top dishes"]},
        ],
        "workflows": [
            {"workflow_name": "Online Order Workflow", "steps": ["Customer browses the menu and adds items + modifiers to cart", "Customer chooses delivery or pickup and a time", "Customer pays online", "System creates the order and shows it on the Kitchen Display", "Kitchen accepts and marks preparing → ready", "Driver is assigned (for delivery) and delivers", "Customer is notified at each step and the order is completed"]},
            {"workflow_name": "Table QR Ordering Workflow", "steps": ["Guest scans the QR code on their table", "System opens the menu for that table", "Guest adds items and places the order", "Order appears on the Kitchen Display tagged with the table", "Kitchen prepares and serves to the table", "Guest pays at the table or counter", "Table is marked free"]},
        ],
        "notifications": [
            {"event": "Order Placed", "recipients": ["customer", "kitchen_staff"], "channels": ["in_app", "email", "sms"]},
            {"event": "Order Ready / Out for Delivery", "recipients": ["customer", "delivery_driver"], "channels": ["sms", "in_app"]},
            {"event": "New Order (Kitchen)", "recipients": ["kitchen_staff"], "channels": ["in_app"]},
            {"event": "Daily Sales Summary", "recipients": ["manager"], "channels": ["email"]},
        ],
        "reports": [
            {"report_name": "Sales Report", "filters": ["date range", "channel", "item", "branch"], "exports": ["PDF", "Excel"]},
            {"report_name": "Top Items Report", "filters": ["date range", "category"], "exports": ["PDF", "Excel"]},
            {"report_name": "Delivery Performance", "filters": ["date range", "driver"], "exports": ["PDF", "Excel"]},
        ],
        "integrations": [
            {"name": "Payment Gateway", "type": "payment", "description": "Online card/wallet payments at checkout.", "required": False},
            {"name": "Google Maps", "type": "maps", "description": "Address autocomplete + delivery distance/ETA.", "required": False},
            {"name": "SMS / WhatsApp", "type": "messaging", "description": "Order status updates to customers.", "required": False},
            {"name": "Third-party Delivery (Uber Eats/Deliveroo)", "type": "delivery", "description": "Push orders to aggregator couriers.", "required": False},
        ],
        "feature_options": ["Online ordering (delivery/pickup)", "Table QR ordering", "Kitchen display board",
                            "Menu & modifier management", "Online payments", "Own delivery / driver app",
                            "Table reservations", "Loyalty & promotions", "Live order tracking", "Ingredient stock alerts"],
        "nfr_focus": ["The kitchen display must update in near real-time (websockets) so new orders appear within ~2 seconds",
                      "Online payments must use a PCI-DSS compliant hosted gateway"],
        "risks": [
            {"area": "Realtime", "risk": "Kitchen board lag", "severity": "Medium", "reason": "Orders that don't appear promptly delay food.", "mitigation": "WebSocket push + audible alert + auto-retry polling."},
            {"area": "Payments", "risk": "Payment Processing", "severity": "High", "reason": "Card handling carries PCI-DSS obligations.", "mitigation": "Use a hosted/tokenised gateway; never store card data."},
        ],
    },
}
