package deploy

import (
	"crypto/rand"
	"encoding/base64"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// The environment contract is the one authoritative answer to what the app
// needs to run, and it never holds a value.
//
// Intake found the names in the source. This decides, for each one, who is
// supposed to supply it: the customer, the agent, the platform, or nobody.
// Everything downstream reads the contract rather than the source: the review
// screen asks for exactly the user_required names, the generated files list
// exactly the production ones, and the deployment gate refuses to go on while
// a required one is unresolved.

// How a variable gets its value.
const (
	// The customer has to type it. A connection string is the example.
	ResolveUser = "user_required"
	// The agent makes one up, once, and stores it in Secrets Manager.
	ResolveGenerate = "auto_generate"
	// The platform sets it — NODE_ENV, PORT, the Vercel variables.
	ResolveProvider = "provider_managed"
	// Nothing has to happen. The app works without it.
	ResolveOptional = "optional"
	// A value that is neither secret nor supplied by the platform.
	ResolveStatic = "static_non_secret"
)

var resolutions = []string{ResolveUser, ResolveGenerate, ResolveProvider, ResolveOptional, ResolveStatic}

// providerManaged are set by whatever is running the app. Asking a customer
// for NODE_ENV would be asking them to get it wrong.
var providerManaged = map[string]bool{
	"NODE_ENV": true, "PORT": true, "CI": true,
	"VERCEL": true, "VERCEL_ENV": true, "VERCEL_URL": true, "VERCEL_REGION": true,
	"AWS_REGION": true, "AWS_DEFAULT_REGION": true,
}

// autoGenerated are secrets whose only requirement is that they be secret, so
// there is nothing to ask anybody for.
var autoGenerated = map[string]bool{"AUTH_SECRET": true, "NEXTAUTH_SECRET": true}

// DeployerInjected are written by the deployment once it knows the address the
// app is reachable at, which is not knowable before it is deployed.
var DeployerInjected = []string{"BETTER_AUTH_URL", "BASE_URL"}

// developmentNames are the Studio's own devtools hooks. They exist in the
// generated app and mean nothing in production.
var developmentNames = map[string]bool{
	"AGENTFORGE_DEVTOOLS_SRC": true, "NEXT_PUBLIC_AGENTFORGE_DEVTOOLS_SRC": true,
}

// devCondition is a test for development mode. A variable only ever read
// inside one is a variable production never needs.
var devCondition = regexp.MustCompile(
	`(?i)NODE_ENV\s*(?:===|==)\s*['"]development['"]|NODE_ENV\s*(?:!==|!=)\s*['"]production['"]`)

// DiscoverContract decides how every variable the app reads is supplied.
// serviceRoot is where the sources were read from, so a variable can be
// checked for being development-only; it may be empty.
func DiscoverContract(service Service, serviceRoot string) Contract {
	entries := map[string]EnvEntry{}

	for _, variable := range service.Environment {
		name := strings.ToUpper(variable.Name)
		developmentOnly := developmentOnly(name, variable.Sources, serviceRoot)
		public := strings.HasPrefix(name, "NEXT_PUBLIC_")

		entry := EnvEntry{
			Name:            name,
			Required:        variable.Required && !developmentOnly,
			Secret:          variable.Secret && !public,
			Scope:           variable.Scope,
			Sources:         unique(variable.Sources),
			Resolution:      ResolveUser,
			Public:          public,
			DevelopmentOnly: developmentOnly,
		}
		if public {
			// A public name is compiled into the bundle and read at runtime,
			// so it has to be present for both.
			entry.Scope = "both"
		}

		switch {
		case providerManaged[name]:
			entry.Resolution, entry.Required, entry.Secret, entry.ValuePresent = ResolveProvider, true, false, true
		case autoGenerated[name]:
			entry.Resolution, entry.Required, entry.Secret, entry.ValuePresent = ResolveGenerate, true, true, true
		case name == "MONGODB_URI":
			// Nobody but the customer knows their database.
			entry.Resolution, entry.Required, entry.Secret = ResolveUser, true, true
		case name == "BETTER_AUTH_SECRET":
			entry.Resolution, entry.Required, entry.Secret = ResolveOptional, false, false
			if service.HasBetterAuth {
				entry.Resolution, entry.Required, entry.Secret = ResolveGenerate, true, true
			}
			entry.ValuePresent = true
		case developmentOnly:
			entry.Resolution, entry.Required, entry.ValuePresent = ResolveOptional, false, true
			if public {
				entry.Secret = false
			}
		case public:
			entry.Resolution, entry.Secret = ResolveOptional, false
			if entry.Required {
				entry.Resolution = ResolveUser
			}
		}
		entries[name] = entry
	}

	// A project that imports a database but never names the variable still
	// needs one, and the same for auth.
	if service.HasMongoDB {
		if _, ok := entries["MONGODB_URI"]; !ok {
			entries["MONGODB_URI"] = EnvEntry{
				Name: "MONGODB_URI", Required: true, Secret: true,
				Scope: "runtime", Resolution: ResolveUser, Sources: []string{},
			}
		}
	}
	if service.HasBetterAuth {
		if _, ok := entries["BETTER_AUTH_SECRET"]; !ok {
			entries["BETTER_AUTH_SECRET"] = EnvEntry{
				Name: "BETTER_AUTH_SECRET", Required: true, Secret: true,
				Scope: "runtime", Resolution: ResolveGenerate, ValuePresent: true, Sources: []string{},
			}
		}
	}

	contract := Contract{Entries: make([]EnvEntry, 0, len(entries))}
	for _, name := range sortedKeys(entries) {
		contract.Entries = append(contract.Entries, entries[name])
	}
	return contract
}

// Resolve settles the contract against what the customer supplied, and returns
// the values separately from the contract — the contract is stored and shown,
// the values go straight to Secrets Manager and are never written down.
func ResolveContract(contract Contract, supplied map[string]string) (Contract, map[string]string, error) {
	given := map[string]string{}
	for key, value := range supplied {
		given[strings.ToUpper(strings.TrimSpace(key))] = value
	}

	resolved := Contract{Entries: make([]EnvEntry, 0, len(contract.Entries))}
	values := map[string]string{}
	seen := map[string]bool{}

	for _, entry := range contract.Entries {
		if seen[entry.Name] {
			return contract, nil, badRequest("Duplicate environment variable: " + entry.Name)
		}
		seen[entry.Name] = true

		value := strings.TrimSpace(given[entry.Name])
		switch entry.Resolution {
		case ResolveUser:
			entry.ValuePresent = value != ""
			if value != "" {
				values[entry.Name] = value
			}
		case ResolveGenerate:
			if value == "" {
				value = token()
			}
			values[entry.Name] = value
			entry.ValuePresent = true
		case ResolveStatic:
			if value != "" {
				values[entry.Name] = value
			}
			entry.ValuePresent = value != "" || !entry.Required
		case ResolveProvider, ResolveOptional:
			if value != "" {
				values[entry.Name] = value
			}
			entry.ValuePresent = true
		default:
			entry.ValuePresent = false
		}
		resolved.Entries = append(resolved.Entries, entry)
	}
	return resolved, values, nil
}

// CheckContract is what has to be true before a deployment may go ahead. It
// returns every problem rather than the first, because a customer filling in a
// form should be told all of it at once.
func CheckContract(contract Contract) []string {
	problems := []string{}
	seen := map[string]bool{}
	for _, entry := range contract.Entries {
		if seen[entry.Name] {
			problems = append(problems, "Duplicate environment variable: "+entry.Name)
		}
		seen[entry.Name] = true

		if !contains(resolutions, entry.Resolution) {
			problems = append(problems, "Environment variable "+entry.Name+" has no supported resolution")
		}
		if entry.Required && !entry.ValuePresent {
			problems = append(problems, "Required environment variable "+entry.Name+" is unresolved")
		}
		if entry.Public && entry.Secret {
			problems = append(problems,
				"Public environment variable "+entry.Name+" cannot be classified as a secret")
		}
		if providerManaged[entry.Name] && entry.Resolution != ResolveProvider {
			problems = append(problems, "Platform variable "+entry.Name+" must be provider managed")
		}
	}
	return problems
}

// ProductionEntries are the variables a running deployment actually needs.
func ProductionEntries(contract Contract) []EnvEntry {
	out := []EnvEntry{}
	for _, entry := range contract.Entries {
		if !entry.DevelopmentOnly && entry.Resolution != ResolveOptional {
			out = append(out, entry)
		}
	}
	return out
}

// Unresolved are the required variables still waiting for a value.
func Unresolved(contract Contract) []EnvEntry {
	out := []EnvEntry{}
	for _, entry := range contract.Entries {
		if entry.Required && !entry.ValuePresent {
			out = append(out, entry)
		}
	}
	return out
}

// developmentOnly reports whether every place the app reads this variable is
// inside a development-mode branch. One unguarded read makes it production's
// problem too.
func developmentOnly(name string, sources []string, serviceRoot string) bool {
	if developmentNames[name] {
		return true
	}
	if serviceRoot == "" || len(sources) == 0 {
		return false
	}
	pattern, err := regexp.Compile(
		`process\.env(?:\.` + regexp.QuoteMeta(name) + `|\[['"]` + regexp.QuoteMeta(name) + `['"]\])`)
	if err != nil {
		return false
	}

	reads, inDevelopment := 0, 0
	for _, source := range sources {
		body, err := os.ReadFile(filepath.Join(serviceRoot, filepath.FromSlash(source)))
		if err != nil {
			continue
		}
		text := string(body)
		for _, at := range pattern.FindAllStringIndex(text, -1) {
			reads++
			if guardedByDevelopment(text, at[0]) {
				inDevelopment++
			}
		}
	}
	return reads > 0 && reads == inDevelopment
}

// guardedByDevelopment reports whether one read sits inside a development-mode
// branch. Finding the test somewhere above the read is not enough — the block
// it opened may have closed again — so the braces between the two are counted:
// still open means the read is inside it.
func guardedByDevelopment(text string, at int) bool {
	from := at - 300
	if from < 0 {
		from = 0
	}
	window := text[from:at]
	found := devCondition.FindAllStringIndex(window, -1)
	if len(found) == 0 {
		return false
	}

	between := window[found[len(found)-1][1]:]
	if !strings.Contains(between, "\n") {
		// Same line: `NODE_ENV === 'development' && process.env.X`, or the
		// ternary form. There is no block to count.
		return true
	}
	depth := 0
	for _, r := range between {
		switch r {
		case '{':
			depth++
		case '}':
			depth--
		}
	}
	return depth > 0
}

// token is a generated secret. It is URL-safe because it ends up in
// configuration files, environment variables and command lines.
func token() string {
	var raw [36]byte
	if _, err := rand.Read(raw[:]); err != nil {
		// Never silently return a weak secret: a caller that cannot have one
		// is better off with a deployment that fails the contract gate.
		return ""
	}
	return base64.RawURLEncoding.EncodeToString(raw[:])
}

func unique(values []string) []string {
	seen := map[string]bool{}
	out := []string{}
	for _, value := range values {
		if !seen[value] {
			seen[value] = true
			out = append(out, value)
		}
	}
	sort.Strings(out)
	return out
}
