"""Next.js stack constraints shared by builder and planner prompts."""
import textwrap
WRITE_FILE_TOOL = {
    "type": "function",
    "function": {
        "name": "write_file",
        "description": "Create or overwrite a file in the project. "
                       "Always send the COMPLETE file content.",
        "parameters": {
            "type": "object",
            "properties": {
                "path": {"type": "string",
                         "description": "Project-relative path, e.g. components/Board.jsx"},
                "content": {"type": "string",
                            "description": "Full file content"},
            },
            "required": ["path", "content"],
        },
    },
}

NEXT_STACK_RULES = textwrap.dedent("""\
    STACK (fixed — do not deviate):
      • Next.js 16 App Router, JavaScript. NO TypeScript, ever.
      • EXTENSIONS — one per role, never both. A file's extension is decided
        by what is in it, and getting this wrong silently breaks the app,
        because the bundler resolves `.jsx` BEFORE `.js`: if both
        `components/Card.js` and `components/Card.jsx` exist, `@/components/Card`
        loads the .jsx and the other is dead code nobody notices.
          .jsx  — anything containing a tag: app/**/page.jsx, app/**/layout.jsx,
                  app/**/error.jsx, app/**/not-found.jsx, components/*.jsx
          .js   — plain modules, which never contain a tag:
                  app/api/**/route.js, lib/*.js
        Never write the same name under both.
      • React 19 function components + hooks
      • Tailwind CSS utility classes for ALL styling
      • MongoDB via the official driver, reached ONLY through @/lib/mongodb
      • Routing is the filesystem: app/page.jsx, app/tasks/page.jsx,
        app/tasks/[id]/page.jsx — there is no router library
      • lucide-react for icons, framer-motion for animation

    PROJECT SHAPE — there is NO src/ directory:
      app/          routes, layouts, pages, route handlers
      components/   reusable UI
      lib/          data access and helpers
      Import across folders with the @/ alias:
        import Card from '@/components/Card'

    DATABASE — THIS IS THE POINT OF THE APP:
      • A local MongoDB is already running and already configured.
        NEVER write connection code, NEVER construct a MongoClient,
        NEVER read process.env.MONGODB_URI yourself.
      • import { getDb, getCollection, serialize, ObjectId } from '@/lib/mongodb'
      • Read and write from Server Components and route handlers only.
      • Seed realistic demo data through lib/seed.js so the app is never empty.
      • NO external APIs, NO API keys, NO Mongoose, NO Prisma.
      • Sign-in, IF this app has one, is ALREADY BUILT — Better Auth against
        this project's MongoDB, generated by AgentForge. Do NOT plan a login route,
        a register route, a logout route, a password hash, a sessions
        collection or a session cookie: every endpoint under /api/auth/*
        already exists and planning one would shadow it. NO next-auth, NO
        Auth0, NO JWT.
        AN APP WITH NO SIGN-IN HAS NO `lib/auth.js` EITHER. It is written
        only when the plan has roles and demo accounts, so in a portfolio,
        a converter or a public catalogue that import does not resolve and
        the build fails on it.
      • Images: Tailwind gradients, inline SVG or emoji. NEVER an external
        image URL that could 404.
    """)
